/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c5c5d3',
        'on-primary-fixed-variant': '#264191',
        background: '#f8f9fa',
        'surface-variant': '#e1e3e4',
        'on-tertiary': '#ffffff',
        'ink-muted': '#999999',
        'surface-bright': '#f8f9fa',
        'on-secondary-container': '#5c647a',
        'ink-secondary': '#666666',
        'on-surface': '#191c1d',
        'tertiary-container': '#001ec9',
        'error-container': '#ffdad6',
        'surface-container-low': '#f3f4f5',
        secondary: '#565e74',
        'surface-container-highest': '#e1e3e4',
        'surface-container-high': '#e7e8e9',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed': '#dfe0ff',
        surface: '#f8f9fa',
        'on-primary-fixed': '#00164e',
        'on-tertiary-container': '#9ba5ff',
        'surface-container': '#edeeef',
        'on-surface-variant': '#444651',
        'primary-fixed': '#dce1ff',
        'on-tertiary-fixed-variant': '#1129d0',
        'surface-tint': '#4059aa',
        'on-primary-container': '#90a8ff',
        'inverse-on-surface': '#f0f1f2',
        'primary-fixed-dim': '#b6c4ff',
        outline: '#757682',
        primary: '#00236f',
        'on-background': '#191c1d',
        'primary-container': '#1e3a8a',
        'secondary-fixed-dim': '#bec6e0',
        'secondary-container': '#dae2fd',
        'tertiary-fixed-dim': '#bdc2ff',
        'inverse-primary': '#b6c4ff',
        'on-secondary-fixed': '#131b2e',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        tertiary: '#00128d',
        'secondary-fixed': '#dae2fd',
        hairline: '#e1e5eb',
        'inverse-surface': '#2e3132',
        'surface-dim': '#d9dadb',
        'on-error-container': '#93000a',
        'ink-black': '#111827',
        'canvas-white': '#ffffff',
        'on-tertiary-fixed': '#000964',
        'on-secondary-fixed-variant': '#3f465c',
        'on-secondary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        gutter: '24px',
        'margin-desktop': '40px',
        'container-max': '1320px',
        'container-min': '1200px',
        'grid-unit': '8px',
      },
      fontFamily: {
        'display-1': ['Noto Sans KR', 'sans-serif'],
        title: ['Noto Sans KR', 'sans-serif'],
        'body-sm': ['Noto Sans KR', 'sans-serif'],
        button: ['Noto Sans KR', 'sans-serif'],
        'headline-2': ['Noto Sans KR', 'sans-serif'],
        eyebrow: ['Noto Sans KR', 'sans-serif'],
        'headline-1-mobile': ['Noto Sans KR', 'sans-serif'],
        'headline-1': ['Noto Sans KR', 'sans-serif'],
        'body-md': ['Noto Sans KR', 'sans-serif'],
      },
      fontSize: {
        'display-1': ['36px', { lineHeight: '1.3', letterSpacing: '-0.02rem', fontWeight: '700' }],
        title: ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        button: ['16px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '700' }],
        'headline-2': ['20px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        eyebrow: ['13px', { lineHeight: '1.3', letterSpacing: '0.02rem', fontWeight: '600' }],
        'headline-1-mobile': ['22px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '700' }],
        'headline-1': ['26px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1320px',
      },
    },
  },
  plugins: [],
};
